title: IIIF Annotation Demo
description: ''
baseurl: '/annotate'
url: ''

github_username: timothyarthur

permalink: pretty
theme: jekyll-swiss-sass-fix
exclude: [Rakefile, Gemfile*, vendor, README.md, LICENSE]

collections:
  viewers:
    output: true

webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
